services:
    srf.metrics.consumer.datadog:
        class: SRF\Bundles\SRFPhpDatadogStatsDBundle\Consumer\DatadogStatsD

    srf.metrics.consumer.monolog:
        class: SRF\Bundles\SRFPhpDatadogStatsDBundle\Consumer\Monolog
        arguments: ['@logger']