services:
    srf.metrics.consumer.datadog:
        class: SRF\Bundles\SRFDatadogStatsDBundle\Consumer\DatadogStatsD

    srf.metrics.consumer.monolog:
        class: SRF\Bundles\SRFDatadogStatsDBundle\Consumer\Monolog
        arguments: ['@logger']